Lmod has detected the following error: Unable to find: "load".



Lmod has detected the following error: Unable to find: "load".



/cluster/work/emilamy/MasterThesisRaw/UtilitiesMaster.py:260: RuntimeWarning: overflow encountered in exp
  return np.exp(old - min(old,new)),np.exp(new - min(old,new))
/cluster/work/emilamy/MasterThesisRaw/UtilitiesMaster.py:239: RuntimeWarning: invalid value encountered in double_scalars
  gamma.pdf(theta_next[i],a=shapes[i],scale=theta_prior[i]/shapes[i])
/cluster/work/emilamy/MasterThesisRaw/UtilitiesMaster.py:239: RuntimeWarning: divide by zero encountered in double_scalars
  gamma.pdf(theta_next[i],a=shapes[i],scale=theta_prior[i]/shapes[i])
/cluster/work/emilamy/dataci/lib/python3.6/site-packages/scipy/stats/_continuous_distns.py:2821: RuntimeWarning: overflow encountered in exp
  return np.exp(self._logpdf(x, a))
/cluster/work/emilamy/MasterThesisRaw/UtilitiesMaster.py:225: RuntimeWarning: invalid value encountered in double_scalars
  gamma.pdf(theta_next[i],a=shapes[i],scale=theta_prior[i]/shapes[i])
/cluster/work/emilamy/MasterThesisRaw/UtilitiesMaster.py:225: RuntimeWarning: divide by zero encountered in double_scalars
  gamma.pdf(theta_next[i],a=shapes[i],scale=theta_prior[i]/shapes[i])
/cluster/work/emilamy/MasterThesisRaw/UtilitiesMaster.py:225: RuntimeWarning: overflow encountered in double_scalars
  gamma.pdf(theta_next[i],a=shapes[i],scale=theta_prior[i]/shapes[i])
/cluster/work/emilamy/MasterThesisRaw/UtilitiesMaster.py:177: RuntimeWarning: divide by zero encountered in log
  h = -np.sum(vp_normalized*np.log(vp_normalized))
/cluster/work/emilamy/MasterThesisRaw/UtilitiesMaster.py:177: RuntimeWarning: invalid value encountered in multiply
  h = -np.sum(vp_normalized*np.log(vp_normalized))
/cluster/work/emilamy/MasterThesisRaw/UtilitiesMaster.py:309: RuntimeWarning: divide by zero encountered in log
  log_posterior += np.log(np.sum(vp)/self.P)
/cluster/work/emilamy/MasterThesisRaw/UtilitiesMaster.py:174: RuntimeWarning: invalid value encountered in true_divide
  return vp/np.sum(vp)
/cluster/work/emilamy/dataci/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:1760: RuntimeWarning: divide by zero encountered in double_scalars
  x = np.asarray((x - loc)/scale, dtype=dtyp)
/cluster/work/emilamy/MasterThesisRaw/UtilitiesMaster.py:223: RuntimeWarning: invalid value encountered in double_scalars
  gamma.pdf(theta_prior[i],a=self.shapes_prior[i],scale=1/self.rates_prior[i])
/cluster/work/emilamy/dataci/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:1760: RuntimeWarning: invalid value encountered in double_scalars
  x = np.asarray((x - loc)/scale, dtype=dtyp)
/cluster/work/emilamy/dataci/lib/python3.6/site-packages/scipy/stats/_distn_infrastructure.py:1769: RuntimeWarning: overflow encountered in true_divide
  place(output, cond, self._pdf(*goodargs) / scale)
/cluster/work/emilamy/MasterThesisRaw/UtilitiesMaster.py:215: RuntimeWarning: invalid value encountered in double_scalars
  proposal = np.array([(np.random.gamma(new_shapes[i],theta[-1][i]/new_shapes[i])) for i in range(self.N)])
/cluster/work/emilamy/dataci/lib/python3.6/site-packages/numpy/linalg/linalg.py:2159: RuntimeWarning: invalid value encountered in det
  r = _umath_linalg.det(a, signature=signature)
Traceback (most recent call last):
  File "LargeScaleOptim7.py", line 21, in <module>
    means,entrs,optms,mutinfs,W,posts = design.onlineDesign_wh(nofreq =False,constant = False, random = False, optimised = True)
  File "/cluster/work/emilamy/MasterThesisRaw/UtilitiesMaster.py", line 798, in onlineDesign_wh
    opts_temp,mutinfs_temp = self.freq_optimiser(means,cov,init = init, optim = True,l=False,inference = inference_optim)
  File "/cluster/work/emilamy/MasterThesisRaw/UtilitiesMaster.py", line 724, in freq_optimiser
    s1temp,s2temp,_ = self.datasim(self.freqs_init[j],means[0],means[1],init = init, optim = optim,l = l)
  File "/cluster/work/emilamy/MasterThesisRaw/UtilitiesMaster.py", line 670, in datasim
    s2[i] = np.random.binomial(1,inverse_logit(W[i]*s1[i-1]+self.b2))
  File "mtrand.pyx", line 3390, in numpy.random.mtrand.RandomState.binomial
  File "_common.pyx", line 374, in numpy.random._common.check_constraint
ValueError: p < 0, p > 1 or p is NaN
