Lmod has detected the following error: Unable to find: "load".



Lmod has detected the following error: Unable to find: "load".



/cluster/work/emilamy/MasterThesisRaw/UtilitiesMaster.py:290: RuntimeWarning: divide by zero encountered in log
  log_posterior += np.log(np.sum(vp)/self.P)
/cluster/work/emilamy/MasterThesisRaw/UtilitiesMaster.py:171: RuntimeWarning: invalid value encountered in true_divide
  return vp/np.sum(vp)
/cluster/work/emilamy/MasterThesisRaw/UtilitiesMaster.py:241: RuntimeWarning: overflow encountered in exp
  return np.exp(old - min(old,new)),np.exp(new - min(old,new))
/cluster/work/emilamy/MasterThesisRaw/UtilitiesMaster.py:174: RuntimeWarning: divide by zero encountered in log
  h = -np.sum(vp_normalized*np.log(vp_normalized))
/cluster/work/emilamy/MasterThesisRaw/UtilitiesMaster.py:174: RuntimeWarning: invalid value encountered in multiply
  h = -np.sum(vp_normalized*np.log(vp_normalized))
/cluster/work/emilamy/MasterThesisRaw/UtilitiesMaster.py:230: RuntimeWarning: invalid value encountered in double_scalars
  prior_ratio = multivariate_normal.pdf(theta_next,mean,cov) / multivariate_normal.pdf(theta_prior,mean,cov)
/cluster/work/emilamy/MasterThesisRaw/UtilitiesMaster.py:230: RuntimeWarning: divide by zero encountered in double_scalars
  prior_ratio = multivariate_normal.pdf(theta_next,mean,cov) / multivariate_normal.pdf(theta_prior,mean,cov)
/cluster/work/emilamy/dataci/lib/python3.6/site-packages/scipy/stats/_continuous_distns.py:2821: RuntimeWarning: overflow encountered in exp
  return np.exp(self._logpdf(x, a))
/cluster/work/emilamy/MasterThesisRaw/UtilitiesMaster.py:236: RuntimeWarning: invalid value encountered in double_scalars
  gamma.pdf(theta_next[i],a=shapes[i],scale=theta_prior[i]/shapes[i])
/cluster/work/emilamy/MasterThesisRaw/UtilitiesMaster.py:236: RuntimeWarning: divide by zero encountered in double_scalars
  gamma.pdf(theta_next[i],a=shapes[i],scale=theta_prior[i]/shapes[i])
Traceback (most recent call last):
  File "LargeScaleOptim9.py", line 21, in <module>
    means,entrs,optms,mutinfs,W,posts = design.onlineDesign_wh(nofreq =False,constant = False, random = False, optimised = True)
  File "/cluster/work/emilamy/MasterThesisRaw/UtilitiesMaster.py", line 686, in onlineDesign_wh
    sample = inference_whole.standardMH()
  File "/cluster/work/emilamy/MasterThesisRaw/UtilitiesMaster.py", line 333, in standardMH
    _,_,old_log_post = self.particle_filter(theta_prior[0],theta_prior[1])
  File "/cluster/work/emilamy/MasterThesisRaw/UtilitiesMaster.py", line 275, in particle_filter
    wp = np.full((self.P,timesteps),np.float(self.w0est))
  File "/cluster/work/emilamy/dataci/lib/python3.6/site-packages/numpy/core/numeric.py", line 314, in full
    a = empty(shape, dtype, order)
numpy.core._exceptions.MemoryError: Unable to allocate 12.4 MiB for an array with shape (50, 32500) and data type float64
slurmstepd: error: *** JOB 209036 ON idun-02-17 CANCELLED AT 2021-05-11T10:09:49 ***
